from lib import *

CH = dict(
meta=dict(id="A03", title="Diversitatea lumii vii și conservarea biodiversității", module="A",
  sources=["Fișe sinteză 2012, p.14–20", "Ghid Nominatrix, p.5–13"],
  concepts=["taxoni: specie → gen → familie → ordin → clasă → încrengătură → regn", "nomenclatură binară", "virusuri: caractere, ADN/ARN, viroze",
            "Monera (bacterii), Protista (euglena, sporozoare), Fungi (ascomicete, bazidiomicete), Plantae (alge, briofite, pteridofite, gimnosperme, angiosperme)",
            "Animalia: celenterate, platelminți, nematelminți, anelide, moluște, artropode, cordate (5 clase)", "specii ocrotite din România"],
  bac_slots=["I.A", "I.B", "I.C", "I.D"], prereq=["A01"], big_ideas=["adaptare–evoluție", "structură–funcție"]),

gr=[
 G("Vertebrate", "Sunt vertebrate:", ["arahnidele", "amfibienii", "celenteratele", "moluștele"], 1,
   "Vertebratele aparțin încrengăturii cordate: pești, amfibieni, reptile, păsări, mamifere.", {0: "M08", 2: "M08", 3: "M08"}, "C", 1, "Subiect bac 2025 I.C.1"),
 G("Regnuri", "Briofitele și pteridofitele aparțin regnului:", ["Fungi", "Monera", "Plante", "Protiste"], 2,
   "Briofitele (mușchi) și pteridofitele (ferigi) sunt plante: avasculare, respectiv vasculare fără flori.", {0: "M08", 1: "M08", 3: "M08"}, "C", 1, "Simulare 2026 I.C.1"),
 G("Moluște", "Cefalopodele sunt:", ["artropode", "celenterate", "moluște", "nematelminți"], 2,
   "Moluștele au trei clase: gasteropode, lamelibranhiate, cefalopode (sepii, caracatițe).", {0: "M08", 1: "M08", 3: "M08"}, "C", 1, "Simulare 2026 I.C.2"),
 G("Virusuri", "Virusurile:", ["au organizare celulară", "conțin ADN sau ARN", "au metabolism propriu", "se multiplică în afara celulei-gazdă"], 1,
   "Sunt entități infecțioase acelulare, fără metabolism propriu, paraziți intracelulari, cu un singur tip de acid nucleic.", {0: "M12", 2: "M12", 3: "M12"}, "C", 1, "Fișe p.15"),
 G("Virusuri ARN", "Virusul care conține ARN este:", ["virusul variolei", "virusul gripal", "virusul herpetic", "virusul varicelei"], 1,
   "Gripa, HIV și turbarea sunt produse de ribovirusuri (ARN); variola, herpesul, varicela de adenovirusuri (ADN).", {0: "M12", 2: "M12", 3: "M12"}, "C", 2, "Fișe p.15"),
 G("Monocotiledonate", "Este plantă monocotiledonată:", ["fasolea", "floarea-soarelui", "porumbul", "cartoful"], 2,
   "Grâul, porumbul, ceapa, lalea sunt monocotiledonate (un cotiledon); fasolea, floarea-soarelui, cartoful sunt dicotiledonate.", {0: "M10", 1: "M10", 3: "M10"}, "C", 1, "Fișe p.17"),
 G("Gimnosperme", "Gimnospermele se caracterizează prin:", ["semințe închise în fruct", "flori cu ovar", "semințe golașe", "vase lemnoase cu trahee"], 2,
   "Gimnospermele (conifere) au flori incomplete, fără ovar; semințele nu sunt închise în fruct.", {0: "M09", 1: "M09", 3: "M09"}, "C", 1, "Fișe p.17"),
 G("Euglena", "Euglena verde:", ["este fungi", "se deplasează cu ajutorul flagelului", "este exclusiv heterotrofă", "are perete celular chitinos"], 1,
   "Euglena este protistă: autotrofă la lumină, heterotrofă la întuneric; are stigmă și flagel.", {0: "M08", 2: "M16", 3: "M04"}, "C", 2, "Fișe p.16"),
 G("Sporozoare", "Plasmodiul malariei aparține:", ["sporozoarelor", "bacteriilor", "ascomicetelor", "algelor verzi"], 0,
   "Sporozoarele sunt protiste imobile, exclusiv parazite; plasmodiul distruge globulele roșii și e transmis de țânțarul Anofel.", {1: "M08", 2: "M08", 3: "M08"}, "C", 2, "Fișe p.16"),
 G("Ciuperci", "Drojdiile și mucegaiul verde-albăstrui (Penicillium) sunt:", ["bazidiomicete", "ascomicete", "licheni", "protiste"], 1,
   "Ascomicetele cuprind drojdii, Penicillium, Aspergillus, Candida; bazidiomicetele sunt ciupercile cu picior și pălărie.", {0: "M08", 2: "M08", 3: "M08"}, "C", 2, "Fișe p.16"),
 G("Platelminți", "Viermele de gălbează este:", ["trematod", "cestod", "nematod", "oligochet"], 0,
   "Viermele de gălbează (trematod) parazitează ficatul oilor; tenia este cestod; limbricul nematod.", {1: "M08", 2: "M08", 3: "M08"}, "C", 2, "Fișe p.18"),
 G("Artropode", "Păianjenul este:", ["insectă", "crustaceu", "arahnidă", "moluscă"], 2,
   "Arahnidele includ scorpioni, căpușe, păianjeni.", {0: "M08", 1: "M08", 3: "M08"}, "C", 1, "Fișe p.18"),
 G("Amfibieni", "Adulții amfibienilor respiră:", ["numai prin branhii", "pulmonar și cutanat", "numai pulmonar", "prin trahei"], 1,
   "Larvele au respirație branhială; adulții respiră pulmonar și cutanat; fecundația este externă.", {0: "M11", 2: "M11", 3: "M11"}, "C", 2, "Fișe p.18–19"),
 G("Reptile", "Reptilele au tegument:", ["subțire, umed, fără solzi", "uscat, cu solzi cornoși", "cu pene", "cu păr"], 1,
   "Tegumentul reptilelor este îngroșat, uscat, cu solzi cornoși sau plăci, fără glande; năpârlesc.", {0: "M11", 2: "M11", 3: "M11"}, "C", 1, "Fișe p.19"),
 G("Păsări", "Păsările sunt:", ["poichiloterme, cu oase pneumatice", "homeoterme, cu oase pneumatice", "homeoterme, vivipare", "poichiloterme, cu glande mamare"], 1,
   "Păsările sunt homeoterme, ovipare, cu oase pneumatice și stern cu carenă (carenate).", {0: "M11", 2: "M11", 3: "M11"}, "C", 2, "Fișe p.19"),
 G("Mamifere", "Delfinul și balena fac parte din ordinul:", ["pinipede", "cetacee", "rozătoare", "primate"], 1,
   "Cetaceele (balene, delfini, cașaloți) sunt mamifere placentare acvatice; focile și morsele sunt pinipede.", {0: "M08", 2: "M08", 3: "M08"}, "C", 2, "Fișe p.20"),
 G("Păsări acarenate", "Este pasăre acarenată:", ["barza", "struțul african", "porumbelul", "bufnița"], 1,
   "Acarenatele (fără carenă): struț, casuar, kiwi.", {0: "M11", 2: "M11", 3: "M11"}, "C", 2, "Fișe p.19"),
 G("Alge", "Pigmentul brun predominant la algele brune este:", ["ficoeritrina", "fucoxantina", "ficocianina", "carotenul"], 1,
   "Algele brune (Phaeophyta: Fucus, Sargassum) au clorofilă și fucoxantină; algele roșii au ficoeritrină și ficocianină.", {0: "M08", 2: "M08", 3: "M08"}, "C", 3, "Fișe p.17"),
 G("Specii ocrotite", "Este specie ocrotită în România:", ["porumbelul", "floarea-de-colț", "mărul", "grâul"], 1,
   "Plante ocrotite: floarea de colț, bujorul românesc, laleaua pestriță, papucul doamnei; animale: dropia, cocoșul de munte, capra neagră.", {0: "M08", 2: "M08", 3: "M08"}, "C", 1, "Fișe p.20"),
],

af=[
 AF("Virusuri", "Virusurile au organizare celulară.", False, "Virusurile au organizare acelulară.", "Sunt entități infecțioase, parazite intracelular.", "M12"),
 AF("Gimnosperme", "Gimnospermele au semințele închise în fruct.", False, "Angiospermele au semințele închise în fruct.", "Gimnospermele au semințe golașe.", "M09"),
 AF("Monera", "Regnul Monera cuprinde organisme procariote.", True, None, "Bacterii și cianobacterii, cu nucleoid."),
 AF("Fungi", "Peretele celular al fungilor conține chitină.", True, None, "Plante: celuloză; procariote: mureină.", "M04"),
 AF("Moluște", "Sepia este o moluscă din clasa gasteropodelor.", False, "Sepia este o moluscă din clasa cefalopodelor.", "Gasteropode: melcul de livadă; cefalopode: sepii, caracatițe.", "M08"),
 AF("Mamifere", "Mamiferele sunt vertebrate homeoterme și vivipare.", True, None, "Au glande mamare, fecundație internă."),
 AF("Reptile", "Reptilele au fecundație externă.", False, "Reptilele au fecundație internă.", "Amfibienii și peștii au, în general, fecundație externă.", "M11"),
 AF("Plasmodiu", "Plasmodiul malariei este o bacterie.", False, "Plasmodiul malariei este un sporozoar.", "Este protistă parazită; distruge globulele roșii.", "M08"),
],

cp=[
 CP("Taxoni", "Unitatea de bază în clasificarea lumii vii este ............ . Orice organism are un nume format din două cuvinte, numit nomenclatură ............ .", ["specia", "binară"]),
 CP("Angiosperme", "Plantele cu semințe închise în fruct se numesc ............, iar cele cu semințe golașe se numesc ............ .", ["angiosperme", "gimnosperme"]),
 CP("Virusuri", "Virusurile au material genetic reprezentat de o moleculă de ............ sau de ............ .", ["ADN", "ARN"]),
],

ex=[
 EX("Clase de vertebrate", "Dați două exemple de clase de vertebrate; scrieți câte o caracteristică.",
    [("amfibieni", "tegument subțire, umed, fără solzi; larvele respiră branhial"), ("reptile", "tegument uscat, cu solzi cornoși; fecundație internă"),
     ("păsări", "homeoterme, cu oase pneumatice și aripi"), ("mamifere", "au glande mamare și păr; sunt vivipare")]),
 EX("Regnuri", "Dați două exemple de regnuri; scrieți câte o caracteristică.",
    [("Monera", "organisme procariote, unicelulare"), ("Fungi", "eucariote heterotrofe, cu perete chitinos"), ("Plante", "eucariote pluricelulare fotoautotrofe")]),
 EX("Insecte", "Dați două exemple de insecte și o importanță a insectelor.",
    [("albina", "produce miere și polenizează florile"), ("fluturele alb al verzei", "dăunător al verzei")]),
],

st=[
 ST("Plante", "III.2.a", "Precizați trei exemple de plante gimnosperme.",
    "Brad, molid, pin (de asemenea tisă, zadă/lariță, ienupăr).", ["trei exemple corecte"], "C", 1, "Fișe p.17"),
 ST("Fungi", "III.2.b", "Explicați importanța ciupercilor saprofite.",
    "Ciupercile saprofite descompun resturile organice și asigură circuitul materiei în natură; unele sunt folosite în producerea alcoolului, a pâinii și a antibioticelor (penicilina).",
    ["descompunători", "circuitul materiei", "aplicații: alcool, antibiotice"], "U", 2, "Fișe p.16"),
],

en=[
 EN("Animale", "Construiți patru enunțuri afirmative, câte două pentru fiecare conținut: păsările; reptilele.",
    ["Păsările", "Reptilele"],
    ["Păsările sunt vertebrate homeoterme adaptate zborului.", "Scheletul păsărilor are oase pneumatice, iar sternul are carenă.",
     "Reptilele au tegumentul uscat acoperit cu solzi cornoși.", "Reptilele au respirație pulmonară și fecundație internă."]),
],

me=[
 ME("Virusuri", "Virusurile", ["acelular", "capsidă", "acid nucleic", "parazit intracelular", "celulă-gazdă", "viroză"],
    "Virusurile sunt entități acelulare, formate din capsidă proteică și un acid nucleic, ADN sau ARN. Ele sunt paraziți intracelulari, care se multiplică numai în celula-gazdă. Bolile produse se numesc viroze, de exemplu gripa."),
],

gl=[
 ("taxon", "Unitate de clasificare: specie, gen, familie, ordin, clasă, încrengătură, regn."),
 ("specie", "Unitatea de bază a clasificării; indivizi înrudiți care se încrucișează dând descendenți fertili."),
 ("nomenclatură binară", "Denumirea organismelor prin două cuvinte latine: gen + specie (Carl Linné)."),
 ("virus", "Entitate infecțioasă acelulară, cu ADN sau ARN, parazit intracelular."),
 ("adenovirus (dezoxiribovirus)", "Virus cu ADN: variola, herpesul, varicela."),
 ("ribovirus", "Virus cu ARN: gripa, HIV, turbarea."),
 ("viroză", "Boală produsă de virusuri."),
 ("bacterioză", "Boală produsă de bacterii: sifilis, tuberculoză, holeră."),
 ("micoză", "Boală produsă de ciuperci."),
 ("micoriză", "Simbioză între o ciupercă și rădăcina unei plante."),
 ("lichen", "Simbioză între o algă verde (sau cianobacterie) și o ciupercă."),
 ("tal", "Corp neîmpărțit în rădăcină, tulpină și frunze, la plantele avasculare."),
 ("cormofite", "Plante vasculare cu rădăcină, tulpină și frunze (corm)."),
 ("briofite", "Mușchi; plante avasculare evoluate."),
 ("pteridofite", "Ferigi; plante vasculare fără flori și semințe, care se înmulțesc prin spori."),
 ("gimnosperme", "Conifere, cu semințe golașe, fără ovar."),
 ("angiosperme", "Plante cu flori complete, cu semințe închise în fruct."),
 ("dicotiledonate", "Angiosperme cu două cotiledoane."),
 ("monocotiledonate", "Angiosperme cu un singur cotiledon."),
 ("homeoterm", "Organism cu temperatura corpului constantă (păsări, mamifere)."),
 ("poichiloterm", "Organism cu temperatura corpului variabilă."),
 ("carenate / acarenate", "Păsări cu / fără carenă pe stern."),
 ("biodiversitate", "Varietatea speciilor și a ecosistemelor; conservată prin specii ocrotite, rezervații, parcuri naționale."),
],

cd=[
 ("Care este ordinea taxonilor de la specie la regn?", "Specie, gen, familie, ordin, clasă, încrengătură, regn."),
 ("Care sunt cele 5 regnuri?", "Monera, Protista, Fungi, Plantae, Animalia."),
 ("Ce tipuri de virusuri după acidul nucleic?", "Adenovirusuri (ADN) și ribovirusuri (ARN)."),
 ("Exemple de viroze?", "Gripa, herpesul, varicela, rujeola, hepatita, SIDA."),
 ("Cele cinci clase de vertebrate?", "Pești, amfibieni, reptile, păsări, mamifere."),
 ("Clasele de moluște și câte un exemplu?", "Gasteropode (melc), lamelibranhiate (scoică), cefalopode (sepie)."),
 ("Clasele de artropode și câte un exemplu?", "Arahnide (păianjen), crustacei (rac), insecte (albină)."),
 ("Exemple de plante ocrotite în România?", "Floarea de colț, bujorul românesc, laleaua pestriță, papucul doamnei, tisa, laricea."),
 ("Exemple de animale ocrotite în România?", "Dropia, cocoșul de munte, pelicanul, lopătarul, capra neagră, râsul."),
],

cmp=[
 dict(title="Gimnosperme vs angiosperme", cols=["Criteriu", "Gimnosperme", "Angiosperme"],
      rows=[["Floare", "incompletă, fără ovar (conuri)", "completă, cu ovar"], ["Sămânță", "golașă, neînchisă în fruct", "închisă în fruct"], ["Fruct", "nu se formează", "se formează din ovar"],
            ["Exemple", "brad, molid, pin, tisă", "dicotiledonate și monocotiledonate"]]),
 dict(title="Clase de vertebrate", cols=["Clasă", "Tegument", "Respirație", "Fecundație", "Temperatura"],
      rows=[["Pești", "solzi", "branhială", "externă sau internă", "poichiloterm"], ["Amfibieni", "subțire, umed, fără solzi", "branhială (larve), pulmonară și cutanată (adulți)", "externă", "poichiloterm"],
            ["Reptile", "uscat, cu solzi cornoși", "pulmonară", "internă", "poichiloterm"], ["Păsări", "pene, puf", "pulmonară", "internă", "homeoterm"], ["Mamifere", "păr, glande mamare", "pulmonară", "internă", "homeoterm"]]),
],
)
