from lib import *

CH = dict(
meta=dict(id="A08", title="Digestia și sistemul digestiv la mamifere; boli digestive", module="A",
  sources=["Fișe sinteză 2012, p.7–10"],
  concepts=["digestie intracelulară (fagocitoză) vs extracelulară", "nutrimente: glucoză, acizi grași, glicerol, aminoacizi", "tubul digestiv: cavitate bucală → faringe → esofag → stomac → intestin subțire → intestin gros",
            "stomac unicameral / tetracameral (rumegătoare)", "glande anexe: salivare, ficat (bila, fără enzime), pancreas (suc pancreatic)", "enzime: amilază, lipază, tripsină, pepsină",
            "boli: gastrită, ulcer gastroduodenal, toxiinfecții alimentare, hepatită virală acută"],
  bac_slots=["I.C", "I.D", "II.A", "III.1"], prereq=["A01", "A05"], big_ideas=["structură–funcție", "homeostazie"]),

gr=[
 G("Bila și sucul pancreatic", "Bila și sucul pancreatic au în comun următoarea caracteristică:",
   ["conțin lipaze cu rol în digestia lipidelor emulsionate", "participă la digestia intestinală a alimentelor", "sunt sucuri digestive lipsite de enzime", "transformă chimic oligopeptidele în aminoacizi"], 1,
   "Ambele se varsă în duoden și participă la digestia intestinală; bila nu conține enzime, iar sucul pancreatic conține enzime (tripsină, lipază, amilază).",
   {0: "M17", 2: "M17", 3: "M17"}, "U", 2, "Subiect bac 2025 I.C.5"),
 G("Bila", "Bila:", ["conține enzime lipolitice", "conține săruri biliare cu rol în emulsionarea grăsimilor", "se produce în vezica biliară", "este secretată de pancreas"], 1,
   "Ficatul secretă bila, care se acumulează în vezica biliară; sărurile biliare emulsionează și facilitează absorbția grăsimilor; bila nu conține enzime.",
   {0: "M17", 2: "M18", 3: "M18"}, "C", 1, "Fișe p.9"),
 G("Amilaza salivară", "Digestia glucidelor începe în:", ["stomac", "cavitatea bucală", "duoden", "intestinul gros"], 1,
   "Amilaza salivară (ptialina) descompune glucidele până la dextrine și maltoză.",
   {0: "M17", 2: "M17", 3: "M17"}, "C", 1, "Fișe p.8–9"),
 G("Pepsina", "Pepsina din sucul gastric hidrolizează:", ["glucidele", "lipidele", "proteinele până la albumoze și peptone", "acizii nucleici"], 2,
   "Sucul gastric conține enzime proteolitice (pepsina).", {0: "M17", 1: "M17", 3: "M17"}, "C", 1, "Fișe p.8"),
 G("Intestinul subțire", "Absorbția nutrimentelor se realizează predominant la nivelul:", ["stomacului", "intestinului subțire", "esofagului", "rectului"], 1,
   "La nivelul intestinului subțire se încheie digestia și are loc absorbția.", {0: "M17", 2: "M18", 3: "M18"}, "C", 1, "Fișe p.8"),
 G("Glande anexe", "Sunt glande anexe ale tubului digestiv:", ["tiroida și hipofiza", "glandele salivare, ficatul, pancreasul", "suprarenalele și timusul", "glandele sudoripare"], 1,
   "Glandele anexe: salivare (parotide, sublinguale, submandibulare), ficat, pancreas exocrin.", {0: "M18", 2: "M18", 3: "M18"}, "C", 1, "Fișe p.7"),
 G("Stomac rumegătoare", "Stomacul tetracameral al rumegătoarelor este alcătuit din:", ["burduf, ciur, foios, cheag", "cardia, fund, corp, pilor", "duoden, jejun, ileon, cecum", "colon, rect, cecum, apendice"], 0,
   "La ierbivorele rumegătoare hrana trece: cavitate bucală → burduf → ciur → cavitate bucală (rumegat) → foios → cheag.", {1: "M18", 2: "M18", 3: "M18"}, "C", 2, "Fișe p.8"),
 G("Lungimea intestinului", "Intestinul subțire este lung la:", ["carnivore", "ierbivore", "omnivore", "păsări"], 1,
   "Este scurt la carnivore, mediu la omnivore, lung la ierbivore.", {0: "M18", 2: "M18", 3: "M18"}, "C", 2, "Fișe p.8"),
 G("Duoden", "Duodenul:", ["este porțiunea mobilă, cu anse intestinale", "are formă de potcoavă, în care se varsă secrețiile pancreasului și ficatului", "se deschide în esofag", "este un segment al intestinului gros"], 1,
   "Duodenul este porțiunea fixă a intestinului subțire.", {0: "M18", 2: "M18", 3: "M18"}, "C", 2, "Fișe p.8"),
 G("Intestin gros", "Intestinul gros cuprinde:", ["duoden, jejun, ileon", "cecum, colon, rect", "faringe, esofag, stomac", "ficat, pancreas, vezică biliară"], 1,
   "La nivelul său au loc fermentații și putrefacții; se formează materiile fecale.", {0: "M18", 2: "M18", 3: "M18"}, "C", 1, "Fișe p.8"),
 G("Digestie intracelulară", "Digestia intracelulară este caracteristică:", ["mamiferelor", "protozoarelor și spongierilor", "păsărilor", "reptilelor"], 1,
   "Se realizează prin fagocitoză și pinocitoză, cu vacuole digestive; la protozoare, spongieri, celenterate și unele celule animale (leucocite).", {0: "M17", 2: "M17", 3: "M17"}, "C", 1, "Fișe p.7"),
 G("Ficat", "Ficatul:", ["este situat în cavitatea toracică", "este localizat subdiafragmatic, în loja hepatică", "produce suc pancreatic", "nu secretă nimic"], 1,
   "Ficatul (~1500 g) este în cavitatea abdominală, subdiafragmatic.", {0: "M18", 2: "M18", 3: "M18"}, "C", 1, "Fișe p.9"),
 G("Pancreas", "Pancreasul exocrin produce:", ["bila", "sucul pancreatic cu tripsină, lipază și amilază", "sucul gastric", "saliva"], 1,
   "Sucul pancreatic conține enzime proteolitice, lipolitice și glicolitice.", {0: "M17", 2: "M17", 3: "M17"}, "C", 1, "Fișe p.9"),
 G("Ulcer", "Una dintre cauzele ulcerului gastroduodenal este:", ["virusul hepatitic A", "bacteria Helicobacter pylori și acțiunea corozivă a HCl", "bacilul Koch", "ciuperca Candida"], 1,
   "Ulcerul: leziuni ale mucoasei, apărând arsuri, foame dureroasă; la nivelul ulcerațiilor se găsesc bacterii rezistente la HCl.", {0: "M26", 2: "M26", 3: "M26"}, "C", 2, "Fișe p.9"),
 G("Hepatita", "Hepatita virală A se transmite prin:", ["sânge contaminat", "alimente contaminate și mâini nespălate", "relații sexuale", "aerul expirat"], 1,
   "Virusurile B și C se transmit prin sânge contaminat, salivă, spermă.", {0: "M26", 2: "M26", 3: "M26"}, "C", 2, "Fișe p.10"),
 G("Sărurile biliare", "Sărurile biliare au rol în:", ["digestia proteinelor", "emulsionarea și absorbția grăsimilor", "digestia glucidelor", "neutralizarea HCl"], 1,
   "Bila nu are enzime, dar emulsionează lipidele, ușurând acțiunea lipazelor.", {0: "M17", 2: "M17", 3: "M17"}, "U", 2, "Fișe p.9"),
],

af=[
 AF("Bila", "Bila conține enzime proteolitice.", False, "Sucul pancreatic conține enzime proteolitice.", "Bila conține săruri biliare, nu enzime.", "M17"),
 AF("Saliva", "Saliva conține amilază salivară.", True, None, "Începe digestia glucidelor în cavitatea bucală."),
 AF("Stomac", "Stomacul omnivorelor (porcul) este foarte voluminos.", False, "Stomacul omnivorelor (porcul) este redus ca dimensiune.", "Este voluminos la ierbivore și carnivore prădătoare.", "M18"),
 AF("Hepatita", "Hepatita virală acută este cauzată de bacterii.", False, "Hepatita virală acută este cauzată de virusuri.", "Virusuri hepatice A, B, C.", "M26"),
 AF("Intestin subțire", "La nivelul intestinului subțire se încheie digestia și are loc absorbția nutrimentelor.", True, None, "Prin vilozități (mucoasă) nutrimentele trec în sânge sau limfă."),
 AF("Faringe", "Faringele este locul de intersecție dintre calea digestivă și cea respiratorie.", True, None, ""),
 AF("Digestie", "Digestia glucidelor produce aminoacizi.", False, "Digestia proteinelor produce aminoacizi.", "Glucide → glucoză; lipide → acizi grași + glicerol.", "M17"),
],

cp=[
 CP("Digestie", "Digestia glucidelor produce ............, iar digestia proteinelor produce ............ .", ["glucoză", "aminoacizi"]),
 CP("Enzime", "Amilaza este o enzimă ............ care digeră ............ .", ["glicolitică (amilolitică)", "glucidele"]),
 CP("Stomac", "Stomacul rumegătoarelor este alcătuit din patru camere: burduf, ciur, foios și ............ .", ["cheag"]),
],

ex=[
 EX("Glande anexe", "Dați două exemple de glande anexe ale tubului digestiv; scrieți câte un rol.",
    [("glandele salivare", "secretă saliva cu amilază, care începe digestia glucidelor"), ("ficatul", "secretă bila, care emulsionează grăsimile"), ("pancreasul exocrin", "secretă suc pancreatic cu enzime pentru glucide, lipide, proteine")]),
 EX("Segmente ale tubului digestiv", "Dați două exemple de segmente ale tubului digestiv; scrieți câte o caracteristică.",
    [("stomacul", "organ cavitar în cavitatea abdominală; în el are loc digestia gastrică cu pepsină"), ("duodenul", "formă de potcoavă; în el se varsă bila și sucul pancreatic"), ("intestinul gros", "cecum, colon, rect; se formează materiile fecale")]),
],

st=[
 ST("Boli digestive", "II.A.a", "Numiți o boală a sistemului digestiv la om (la alegere) precizând: o cauză, o manifestare, două măsuri de prevenire.",
    "Exemplu – gastrita: cauză – iritații produse de alcool, tutun, alimente condimentate sau alterate; manifestare – greață, dureri gastrice, vărsături; prevenire – evitarea alcoolului și a alimentelor alterate, alimentație echilibrată.",
    ["boală corectă", "o cauză", "o manifestare", "două măsuri de prevenire"], "C", 2, "Model după simulare 2026 II.A.a"),
 ST("Rolul bilei", "III.1.b", "Explicați rolul bilei în digestia lipidelor.",
    "Bila conține săruri biliare care emulsionează grăsimile și ușurează acțiunea lipazelor și absorbția lor; bila nu conține enzime.",
    ["săruri biliare", "emulsionarea lipidelor", "nu are enzime"], "U", 2, "Fișe p.9"),
 ST("Intestin subțire", "II.A.b", "Explicați rolul intestinului subțire în nutriția organismului.",
    "La nivelul intestinului subțire se încheie digestia chimică, sub acțiunea sucului intestinal, a bilei și a sucului pancreatic, și are loc absorbția nutrimentelor în sânge și limfă.",
    ["finalizarea digestiei", "sucuri digestive", "absorbția nutrimentelor"], "U", 2),
],

en=[
 EN("Digestie", "Construiți patru enunțuri afirmative, câte două pentru fiecare conținut: ficatul; pancreasul.",
    ["Ficatul", "Pancreasul"],
    ["Ficatul este situat subdiafragmatic, în loja hepatică.", "Ficatul secretă bila, care emulsionează grăsimile.",
     "Pancreasul este o glandă mixtă.", "Sucul pancreatic conține enzime proteolitice, lipolitice și glicolitice."]),
 EN("Digestie", "Construiți patru enunțuri afirmative, câte două pentru fiecare conținut: stomacul; intestinul gros.",
    ["Stomacul", "Intestinul gros"],
    ["Stomacul este un organ cavitar situat în cavitatea abdominală.", "În stomac, pepsina hidrolizează proteinele până la albumoze și peptone.",
     "Intestinul gros este alcătuit din cecum, colon și rect.", "În intestinul gros se formează materiile fecale."]),
],

me=[
 ME("Digestia", "Digestia", ["tub digestiv", "glande anexe", "enzime", "nutrimente", "absorbție", "bila"],
    "Digestia se desfășoară în tubul digestiv, cu participarea glandelor anexe, care secretă sucuri digestive cu enzime. Bila nu conține enzime, dar emulsionează grăsimile. Nutrimentele rezultate sunt absorbite în intestinul subțire."),
],

gl=[
 ("digestie", "Transformările mecanice, fizice și chimice ale substanțelor organice complexe în nutrimente absorbabile."),
 ("nutriment", "Substanță organică simplă, absorbabilă: glucoză, acizi grași, glicerol, aminoacizi."),
 ("fagocitoză", "Înglobarea particulelor solide de către celulă; digestie intracelulară."),
 ("masticație", "Mărunțirea hranei cu dinții, limba, saliva; formează bolul alimentar."),
 ("deglutiție", "Înghițirea; transportul bolului din cavitatea bucală în stomac."),
 ("amilază salivară (ptialină)", "Enzimă din salivă; descompune glucidele până la dextrine și maltoză."),
 ("pepsină", "Enzimă proteolitică din sucul gastric."),
 ("duoden", "Porțiunea fixă a intestinului subțire, în formă de potcoavă; primește bila și sucul pancreatic."),
 ("bilă", "Secreția ficatului; săruri biliare, fără enzime; emulsionează grăsimile."),
 ("suc pancreatic", "Conține tripsină, lipază și amilază pancreatice."),
 ("apendice vermiform", "Organ rudimentar la om, atașat cecumului."),
 ("gastrită", "Inflamația mucoasei gastrice."),
 ("ulcer gastroduodenal", "Leziuni ale mucoasei gastrice sau duodenale; HCl, Helicobacter pylori."),
 ("toxiinfecție alimentară", "Îmbolnăvire prin alimente alterate sau manipulate defectuos."),
],

cd=[
 ("Ce enzime conține sucul pancreatic?", "Tripsină (proteolitică), lipază, amilază."),
 ("Conține bila enzime?", "Nu; conține săruri biliare care emulsionează grăsimile."),
 ("Ce hidrolizează pepsina?", "Proteinele, până la albumoze și peptone."),
 ("Unde începe digestia glucidelor?", "În cavitatea bucală, prin amilaza salivară."),
 ("Care sunt segmentele intestinului gros?", "Cecum, colon, rect."),
 ("Camerele stomacului la rumegătoare?", "Burduf, ciur, foios, cheag."),
 ("Prevenirea hepatitei virale A?", "Igienă a mâinilor, alimente curate, apă potabilă de calitate."),
],

cmp=[
 dict(title="Enzime și produsele lor", cols=["Sediul", "Suc", "Enzime", "Acționează asupra"],
      rows=[["Cavitate bucală", "saliva", "amilază salivară (ptialină)", "glucide → dextrine, maltoză"], ["Stomac", "suc gastric", "pepsină", "proteine → albumoze, peptone"],
            ["Duoden", "suc pancreatic", "tripsină, lipază, amilază", "proteine, lipide, glucide"], ["Duoden", "bilă", "fără enzime (săruri biliare)", "emulsionează grăsimile"],
            ["Intestin subțire", "suc intestinal", "peptidaze, lipază intestinală, dizaharidaze", "încheie digestia"]]),
],
)
