from lib import *

CH = dict(
meta=dict(id="A02", title="Diviziunea celulară: ciclul celular, mitoza, meioza", module="A",
  sources=["Fișe sinteză 2012, p.11–13, 36–37", "Ghid Nominatrix, p.20–22"],
  concepts=["ciclul celular: interfază + diviziune", "diviziune directă (amitoză) vs indirectă (cariochinetică)", "cromozomi: tipuri, 2n/n, autozomi/heterozomi, cariotip uman 2n=46",
            "mitoza: faze (profază, metafază, anafază, telofază), rol", "meioza: etapa reducțională și ecvațională, crossing-over, dansul cromozomilor", "importanța meiozei"],
  bac_slots=["I.C", "I.D", "III.2"], prereq=["A01"], big_ideas=["informație genetică", "variabilitate"]),

gr=[
 G("Meioză – număr de cromozomi", "Fiecare dintre celulele-fiice formate prin diviziunea meiotică a unei celule-mamă cu 2n = 14 cromozomi are:",
   ["n = 7 cromozomi", "n = 14 cromozomi", "2n = 7 cromozomi", "2n = 14 cromozomi"], 0,
   "Meioza reduce numărul de cromozomi la jumătate: din 2n = 14 rezultă celule haploide cu n = 7.",
   {1: "M01", 2: "M01", 3: "M01"}, "A", 1, "Subiect bac 2025 I.C.3"),
 G("Mitoză – număr de cromozomi", "Fiecare dintre celulele-fiice formate prin diviziunea mitotică a unei celule-mamă cu 2n = 28 cromozomi are:",
   ["n = 14 cromozomi", "n = 28 cromozomi", "2n = 14 cromozomi", "2n = 28 cromozomi"], 3,
   "Mitoza păstrează numărul de cromozomi: celulele-fiice sunt diploide, 2n = 28.",
   {0: "M01", 1: "M01", 2: "M01"}, "A", 1, "Simulare 2026 I.C.4"),
 G("Meioză – număr de celule", "Dintr-o celulă-mamă diploidă, prin meioză, se formează:",
   ["două celule diploide", "patru celule haploide", "două celule haploide", "patru celule diploide"], 1,
   "Meioza este formată din etapa reducțională (2 celule n) și etapa ecvațională (4 celule n).",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 1, "Fișe p.36–37"),
 G("Crossing-over", "Crossing-over-ul are loc în:",
   ["metafaza mitozei", "profaza I a meiozei", "anafaza II a meiozei", "telofaza mitozei"], 1,
   "Schimbul de material genetic între cromatide nesurori are loc în profaza I, la nivelul chiasmelor tetradelor.",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 2, "Fișe p.36"),
 G("Fus de diviziune", "Fusul de diviziune ia naștere prin autoduplicarea:",
   ["nucleolului", "centrozomului", "ribozomului", "mitocondriei"], 1,
   "Fusul este format din filamente care unesc cei doi centrozomi situați la polii celulei.",
   {0: "M06", 2: "M06", 3: "M06"}, "C", 1, "Fișe p.11"),
 G("Cariotip uman", "Cariotipul uman normal cuprinde:",
   ["23 autozomi și 23 heterozomi", "44 autozomi și 2 heterozomi", "46 heterozomi", "22 autozomi și 24 heterozomi"], 1,
   "2n = 46: 44 autozomi și 2 heterozomi (XX sau XY).",
   {0: "M44", 2: "M44", 3: "M44"}, "C", 1, "Fișe p.12"),
 G("Diviziune directă", "Diviziunea directă (amitoza):",
   ["are loc la eucariote, cu fus de diviziune", "are loc la procariote, prin strangulare", "formează cromozomi omologi", "este specifică celulelor reproducătoare"], 1,
   "Amitoza are loc la procariote și protiste prin strangulare și formarea unui perete despărțitor; nu are fus de diviziune.",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 2, "Fișe p.11"),
 G("Interfaza", "În interfază, cantitatea de ADN:",
   ["se înjumătățește", "se dublează", "rămâne neschimbată", "dispare"], 1,
   "Interfaza este perioada de sinteză intensă: ARN, proteine, creștere și dublarea ADN-ului.",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 1, "Fișe p.11"),
 G("Placa metafazică", "Dispunerea cromozomilor bicromatidici în placa ecuatorială are loc în:",
   ["profază", "metafază", "anafază", "telofază"], 1,
   "În metafază cromozomii bicromatidici se așază în placa ecuatorială, la centrul fusului.",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 1, "Fișe p.12"),
 G("Rolul mitozei", "Care este rolul mitozei?",
   ["formarea gameților", "creșterea și înlocuirea celulelor uzate", "reducerea numărului de cromozomi", "apariția variabilității prin crossing-over"], 1,
   "Mitoza are loc în celulele somatice și asigură creșterea, dezvoltarea și înlocuirea celulelor.",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 1, "Fișe p.12"),
 G("Telofaza", "În telofaza mitozei:",
   ["se formează tetradele", "se reorganizează membrana nucleară și nucleolii", "se produce crossing-over", "se înjumătățește numărul de cromozomi"], 1,
   "În telofază cromozomii se despiralizează, fusul se dezorganizează, se reorganizează membrana nucleară și nucleolii.",
   {0: "M01", 2: "M01", 3: "M01"}, "C", 2, "Fișe p.12–13"),
],

af=[
 AF("Meioza", "Meioza are loc în celulele somatice.", False, "Meioza are loc în celulele organelor reproducătoare.", "Se desfășoară în testicule și ovare și formează gameții.", "M01"),
 AF("Mitoza", "Prin mitoză, dintr-o celulă-mamă diploidă rezultă două celule-fiice diploide.", True, None, "Celulele-fiice au același număr de cromozomi ca celula-mamă."),
 AF("Notații", "Celulele haploide se notează cu 2n.", False, "Celulele haploide se notează cu n.", "Celulele diploide se notează 2n.", "M40"),
 AF("Dansul cromozomilor", "Dansul cromozomilor (recombinarea intercromozomală) are loc în metafaza I.", True, None, "Perechile de omologi se orientează și migrează la întâmplare."),
 AF("Crossing-over", "Crossing-over-ul asigură recombinarea intercromozomală.", False, "Crossing-over-ul asigură recombinarea intracromozomală.", "Recombinarea intercromozomală este dansul cromozomilor.", "M01"),
 AF("Interfaza", "Interfaza face parte din ciclul celular.", True, None, "Ciclul celular = interfază + diviziune."),
 AF("Etapa reducțională", "Etapa ecvațională a meiozei reduce numărul de cromozomi la jumătate.", False, "Etapa reducțională a meiozei reduce numărul de cromozomi la jumătate.", "Etapa ecvațională este o mitoză.", "M01"),
],

cp=[
 CP("Mitoză/meioză", "Diviziunea ............ asigură creșterea organismului, iar diviziunea ............ formează gameții.", ["mitotică", "meiotică"]),
 CP("Ciclul celular", "Ciclul celular cuprinde ............ și diviziunea celulară.", ["interfaza"]),
 CP("Cariotip uman", "Cariotipul uman are ............ cromozomi, dintre care 44 sunt ............ .", ["46", "autozomi"]),
],

ex=[
 EX("Faze ale mitozei", "Dați două exemple de faze ale mitozei; scrieți câte o caracteristică.",
    [("profaza", "cromatina se condensează formând cromozomi bicromatidici; membrana nucleară și nucleolii se dezorganizează"),
     ("metafaza", "cromozomii bicromatidici se dispun în placa ecuatorială"),
     ("anafaza", "cromozomii monocromatidici migrează spre polii celulei"),
     ("telofaza", "se reorganizează membrana nucleară și nucleolii")]),
 EX("Faze ale meiozei", "Dați două exemple de procese care au loc în profaza I a meiozei.",
    [("formarea bivalenților (tetrade)", "perechi de cromozomi omologi"), ("crossing-over", "schimb de material genetic între cromatide nesurori la nivelul chiasmelor")]),
],

st=[
 ST("Importanța meiozei", "III.2.b", "Precizați un argument în favoarea afirmației: „Meioza menține constant numărul de cromozomi al speciei”.",
    "Meioza reduce numărul de cromozomi de la 2n la n în gameți, iar prin fecundație zigotul redevine 2n, astfel numărul de cromozomi rămâne constant de la o generație la alta.",
    ["2n → n în gameți", "fecundația reface 2n în zigot"], "R", 2),
 ST("Variabilitate", "III.2.b", "Explicați contribuția meiozei la creșterea variabilității genetice.",
    "Prin crossing-over (recombinare intracromozomală, în profaza I) și prin dansul cromozomilor (recombinare intercromozomală, în metafaza I) rezultă gameți cu combinații genetice diferite.",
    ["crossing-over – intracromozomală", "dansul cromozomilor – intercromozomală", "gameți diferiți genetic"], "U", 2),
],

en=[
 EN("Mitoză/meioză", "Construiți patru enunțuri afirmative, câte două pentru fiecare conținut: mitoza; meioza.",
    ["Mitoza", "Meioza"],
    ["Mitoza are loc în celulele somatice diploide.", "Prin mitoză dintr-o celulă-mamă 2n rezultă două celule-fiice 2n.",
     "Meioza se desfășoară în două etape: reducțională și ecvațională.", "Meioza formează patru celule-fiice haploide, care dau gameții."]),
],

me=[
 ME("Meioza", "Meioza", ["celulă diploidă", "etapa reducțională", "crossing-over", "gameți", "haploid", "variabilitate genetică"],
    "Meioza se desfășoară într-o celulă diploidă din organele reproducătoare și are două etape, reducțională și ecvațională. În profaza etapei reducționale are loc crossing-over, care crește variabilitatea genetică. La final rezultă patru celule haploide, care formează gameții."),
 ME("Mitoza", "Mitoza", ["celulă somatică", "interfază", "cromozomi", "fus de diviziune", "celule diploide", "creștere"],
    "Mitoza are loc într-o celulă somatică, după interfază, perioadă în care ADN-ul se dublează. Cromozomii se condensează, se prind de fusul de diviziune și se distribuie în două celule diploide. Procesul asigură creșterea organismului."),
],

gl=[
 ("ciclu celular", "Succesiunea proceselor care asigură creșterea și diviziunea celulei: interfază + diviziune."),
 ("interfază", "Perioada dintre două diviziuni; sinteză de ARN, proteine și dublarea ADN."),
 ("amitoză", "Diviziune directă, prin strangulare, la procariote și protiste; fără fus."),
 ("cariochineză", "Diviziunea nucleului (profază, metafază, anafază, telofază)."),
 ("citochineză", "Diviziunea citoplasmei."),
 ("fus de diviziune", "Structură de filamente între cei doi centrozomi; orientează cromozomii."),
 ("cromozom bicromatidic", "Cromozom format din două cromatide unite prin centromer."),
 ("cromozom monocromatidic", "Cromozom cu o singură cromatidă."),
 ("celulă diploidă (2n)", "Celulă cu două seturi de cromozomi (matern și patern), de exemplu celula somatică."),
 ("celulă haploidă (n)", "Celulă cu un singur set de cromozomi, de exemplu gametul."),
 ("autozomi", "Cromozomi identici la cele două sexe; la om 44."),
 ("heterozomi", "Cromozomi sexului (X și Y); la om 2."),
 ("cariotip", "Totalitatea cromozomilor unei specii; la om 2n = 46."),
 ("etapă reducțională", "Meioza I; reduce numărul de cromozomi la jumătate."),
 ("etapă ecvațională", "Meioza II; de tip mitotic."),
 ("bivalent (tetradă)", "Pereche de cromozomi omologi alipiți în profaza I."),
 ("chiasmă", "Punct de contact între cromatide nesurori ale omologilor."),
 ("crossing-over", "Schimb de material genetic între cromatide nesurori; recombinare intracromozomală."),
 ("dansul cromozomilor", "Distribuirea întâmplătoare a omologilor; recombinare intercromozomală."),
],

cd=[
 ("Care sunt fazele mitozei, în ordine?", "Profază, metafază, anafază, telofază."),
 ("Câte celule și ce ploidie rezultă din mitoză?", "Două celule-fiice diploide (2n)."),
 ("Câte celule și ce ploidie rezultă din meioză?", "Patru celule-fiice haploide (n)."),
 ("Unde are loc crossing-over-ul?", "În profaza I a meiozei."),
 ("Cum se numește meioza I și meioza II?", "Etapa reducțională (I) și etapa ecvațională (II)."),
 ("Care e cariotipul uman?", "2n = 46: 44 autozomi + 2 heterozomi."),
 ("Ce se întâmplă cu ADN-ul în interfază?", "Se dublează."),
],

cmp=[
 dict(title="Mitoză vs meioză", cols=["Criteriu", "Mitoză", "Meioză"],
      rows=[["Tip de celule", "somatice", "din organele reproducătoare"],
            ["Celula-mamă", "2n", "2n"],
            ["Nr. celule-fiice", "2", "4"],
            ["Ploidia celulelor-fiice", "2n", "n"],
            ["Etape", "una", "două: reducțională și ecvațională"],
            ["Crossing-over", "nu", "da (profaza I)"],
            ["Rol", "creștere, înlocuire", "formarea gameților, variabilitate"]]),
],
)
