from lib import *

CH = dict(
meta=dict(id="A01", title="Celula – unitatea structurală și funcțională a vieții", module="A",
  sources=["Fișe sinteză 2012, p.1–4", "Ghid Nominatrix, p.14–19"],
  concepts=["celulă procariotă (perete cu mureină, nucleoid, ribozomi)", "celulă eucariotă: înveliș, citoplasmă, nucleu",
            "membrana celulară – mozaic fluid", "perete celular (celuloză / chitină / mureină)",
            "organite: mitocondrii, RE, ribozomi, Golgi, lizozomi, centrozom, vacuole, plastide",
            "cloroplast: grana, stroma", "nucleu: membrană cu pori, carioplasmă, cromatină, nucleoli", "excepții: hematia matură anucleată"],
  bac_slots=["I.B", "I.C", "I.D", "II.A.b", "III.2"], prereq=[], big_ideas=["structură–funcție", "informație genetică", "energie"]),

gr=[
 G("Organite cu membrană dublă", "Organitul celular cu membrană dublă, care conține ADN propriu, este:",
   ["lizozomul", "mitocondria", "ribozomul", "aparatul Golgi"], 1,
   "Mitocondriile au membrană dublă (externă netedă, internă cu criste) și ADN propriu, fiind autodivizibile.",
   {0: "M02", 2: "M02", 3: "M02"}, "C", 1, "Fișe p.2"),
 G("Perete celular", "Peretele celular de natură chitinoasă este caracteristic celulei:",
   ["vegetale", "bacteriene", "fungice", "animale"], 2,
   "La fungi peretele conține chitină; la plante celuloză; la procariote mureină; celula animală nu are perete.",
   {0: "M04", 1: "M04", 3: "M03"}, "C", 1, "Fișe p.1"),
 G("Celula procariotă", "Celula procariotă se caracterizează prin:",
   ["nucleu delimitat de membrană dublă", "cromozom circular într-un nucleoid", "prezența mitocondriilor", "prezența reticulului endoplasmatic"], 1,
   "Materialul genetic este o moleculă de ADN circulară, dispusă difuz în nucleoid, fără anvelopă nucleară; organitele cu membrană lipsesc.",
   {0: "M05", 2: "M05", 3: "M05"}, "C", 1, "Fișe p.1"),
 G("Lizozomi", "Lizozomii sunt organite cu rol în:",
   ["sinteza proteinelor", "fotosinteză", "digestia intracelulară", "respirația celulară"], 2,
   "Lizozomii conțin enzime hidrolitice și realizează digestia intracelulară (fagocitoza); sunt numeroși în leucocite.",
   {0: "M06", 1: "M06", 3: "M06"}, "C", 1, "Fișe p.3"),
 G("Cloroplast", "Substanța fundamentală a cloroplastului se numește:",
   ["matrix", "stromă", "hialoplasmă", "carioplasmă"], 1,
   "Stroma conține ADN, ARN, ribozomi și este locul fazei de întuneric; matrixul aparține mitocondriei, carioplasma nucleului.",
   {0: "M07", 2: "M06", 3: "M06"}, "C", 2, "Fișe p.3–4"),
 G("Organite specifice", "Sunt specifice celulei vegetale:",
   ["mitocondriile", "plastidele", "ribozomii", "reticulul endoplasmatic"], 1,
   "Plastidele (cloroplaste, cromoplaste, leucoplaste) lipsesc din celula animală; celelalte organite sunt comune.",
   {0: "M03", 2: "M03", 3: "M03"}, "C", 1, "Fișe p.3"),
 G("Membrana celulară", "Membrana celulară:",
   ["este alcătuită dintr-un singur strat fosfolipidic", "este organizată după modelul mozaicului fluid", "este o structură nevie", "lipsește la celula animală"], 1,
   "Membrana are două straturi fosfolipidice străbătute de proteine (mozaic fluid) și este permeabilă selectiv; peretele celular e structura nevie.",
   {0: "M06", 2: "M04", 3: "M03"}, "C", 1, "Fișe p.1"),
 G("Aparat Golgi", "Aparatul Golgi este alcătuit din totalitatea:",
   ["cristelor", "dictiozomilor", "tilacoidelor", "centriolilor"], 1,
   "Dictiozomii sunt formațiuni discoidale cu membrană simplă, aplatizate și suprapuse; din marginile lor se desprind vezicule cu secreții.",
   {0: "M02", 2: "M07", 3: "M06"}, "C", 1, "Fișe p.3"),
 G("Organit fără membrană", "Organitul comun celulelor vegetală și animală, cu rol în sinteza proteinelor, este:",
   ["centrozomul", "cloroplastul", "lizozomul", "ribozomul"], 3,
   "Ribozomii (granulele lui Palade) sunt organite fără membrană, formate din ARN și proteine, sediul biosintezei proteinelor.",
   {0: "M06", 1: "M03", 2: "M06"}, "C", 1, "Fișe p.3; subiect bac 2025"),
 G("Nucleolul", "Nucleolii au rol în:",
   ["biogeneza ribozomilor", "fotosinteză", "digestie intracelulară", "formarea fusului de diviziune"], 0,
   "Nucleolii conțin ARN și participă la biogeneza ribozomilor și la diviziunea celulară.",
   {1: "M06", 2: "M06", 3: "M06"}, "C", 2, "Fișe p.4"),
 G("Excepții nucleare", "Care celulă este anucleată la maturitate?",
   ["hepatocitul", "hematia", "leucocitul", "neuronul"], 1,
   "Hematia adultă și trombocitul nu au nucleu; hepatocitul poate fi binucleat, iar leucocitele și neuronii au nucleu.",
   {0: "M05", 2: "M23", 3: "M05"}, "C", 2, "Ghid Nominatrix p.19"),
 G("Cromozomii în nucleu", "Cromatina nucleară este constituită din:",
   ["ADN, ARN și proteine", "numai ADN", "numai proteine", "lipide și glucide"], 0,
   "Cromatina (ADN, ARN, proteine) formează cromozomii, vizibili la microscop doar în timpul diviziunii celulare.",
   {1: "M06", 2: "M06", 3: "M06"}, "C", 1, "Fișe p.4"),
 G("Plastide de depozitare", "Plastidele care depozitează amidon în tuberculul de cartof se numesc:",
   ["cromoplaste", "oleoplaste", "amiloplaste", "proteoplaste"], 2,
   "Amiloplastele (leucoplaste) depozitează amidon; oleoplastele uleiuri (floarea-soarelui); proteoplastele proteine (semințe).",
   {0: "M06", 1: "M06", 3: "M06"}, "C", 2, "Fișe p.3"),
 G("Celula procariotă – peretele", "Peretele celulei procariote conține:",
   ["celuloză", "chitină", "mureină", "lignină"], 2,
   "Peretele rigid, necelulozic al procariotelor conține mureină.",
   {0: "M04", 1: "M04", 3: "M04"}, "C", 1, "Fișe p.1"),
 G("Mitocondrii – interpretare", "Celulele cu activitate intensă de contracție conțin multe mitocondrii deoarece mitocondriile:",
   ["sintetizează proteine contractile", "realizează oxidarea substanțelor organice cu eliberare de energie", "depozitează apa", "formează fusul de diviziune"], 1,
   "Mitocondriile sunt sediul respirației celulare; energia eliberată este stocată în ATP și folosită la contracție.",
   {0: "M06", 2: "M06", 3: "M06"}, "U", 2, "Fișe p.2; simulare 2026 II.A.b"),
],

af=[
 AF("Ribozomi", "Ribozomii sunt organite celulare cu membrană simplă.", False, "Ribozomii sunt organite celulare fără membrană.", "Ribozomii sunt granule de ribonucleoproteine, lipsite de membrană.", "M02"),
 AF("Perete celular", "Peretele celular lipsește la celula animală.", True, None, "Peretele celular e specific celulei vegetale și fungice."),
 AF("Mitocondrii", "Mitocondriile conțin ADN propriu și sunt autodivizibile.", True, None, "ADN-ul mitocondrial codifică enzime respiratorii."),
 AF("Vacuole", "Vacuolele sunt permanente în celulele animale.", False, "Vacuolele sunt temporare în celulele animale.", "Sunt permanente în celulele vegetale.", "M03"),
 AF("Cromozomi", "Cromozomii pot fi vizualizați la microscop doar în timpul diviziunii celulare.", True, None, "În interfază cromatina e decondensată."),
 AF("Centrozom", "Centrozomul este alcătuit din doi centrioli.", True, None, "Centrioli dispuși perpendicular; dau naștere fusului de diviziune."),
 AF("Plastide", "Cloroplastele conțin pigmenți roșii-portocalii.", False, "Cloroplastele conțin pigmenți verzi (clorofilieni).", "Pigmenții roșii-portocalii se află în cromoplaste.", "M06"),
 AF("Reticul endoplasmatic", "Reticulul endoplasmatic rugos are ribozomi atașați pe membrană.", True, None, "Ribozomii atașați dau aspectul granular (REG)."),
],

cp=[
 CP("Plastide", "Plastidele care depozitează amidon se numesc ............, iar cele care depozitează uleiuri se numesc ............ .", ["amiloplaste", "oleoplaste"]),
 CP("Celula procariotă", "Materialul genetic al celulei procariote este un cromozom ............, situat în ............ .", ["circular", "nucleoid"]),
 CP("Membrana", "Membrana celulară este organizată după modelul ............ ............ .", ["mozaicului", "fluid"], "Răspuns acceptat: mozaic fluid."),
 CP("Respirația celulară", "Procesul de ............ celulară se desfășoară la nivelul ............ .", ["respirație", "mitocondriilor"]),
],

ex=[
 EX("Procariote", "Dați două exemple de componente ale unei celule procariote; scrieți în dreptul fiecărui component câte o caracteristică structurală.",
    [("peretele celular", "rigid, necelulozic, conține mureină"), ("nucleoidul", "conține o moleculă de ADN circular, fără membrană nucleară"), ("ribozomii", "organite fără membrană, formate din ARN și proteine")],
    "Orice două componente cu caracteristica corectă.", src="Subiect bac 2025 I.B"),
 EX("Organite cu membrană dublă", "Dați două exemple de organite cu membrană dublă; scrieți câte o caracteristică.",
    [("mitocondria", "membrana internă formează criste"), ("cloroplastul", "membrana internă formează tilacoide dispuse în grane")]),
 EX("Plastide", "Dați două exemple de plastide nefotosintetizante; scrieți câte un rol.",
    [("amiloplastul", "depozitează amidon"), ("cromoplastul", "conține pigmenți roșii-portocalii și colorează fructele"), ("oleoplastul", "depozitează uleiuri")]),
],

st=[
 ST("Mitocondrii", "II.A.b", "Explicați numărul mare de mitocondrii din celulele țesutului muscular cardiac.",
    "Mitocondriile sunt sediul respirației celulare; la nivelul lor substanțele organice sunt oxidate cu eliberare de energie stocată în ATP. Miocardul se contractă continuu, deci consumă multă energie; de aceea celulele lui conțin multe mitocondrii.",
    ["mitocondria = sediul respirației celulare", "oxidarea substanțelor organice eliberează energie (ATP)", "contracție continuă = consum mare de energie"], "U", 2, "Simulare 2026 II.A.b"),
 ST("Nucleul", "III.2.b", "Precizați un argument în favoarea afirmației: „Nucleul coordonează activitatea celulei”.",
    "Nucleul conține ADN, în care este stocată informația genetică; aceasta determină tipul de proteine (enzime) sintetizate și astfel controlează procesele celulare și diviziunea.",
    ["ADN-ul stochează informația genetică", "informația determină proteinele/enzimele sintetizate", "controlul proceselor celulare și al diviziunii"], "R", 2),
 ST("Cloroplast", "III.2.b", "Explicați de ce fotosinteza se desfășoară în cloroplaste.",
    "Cloroplastele conțin pigmenți clorofilieni în tilacoide (grana), care absorb energia luminoasă; în stromă se găsesc enzimele și ADN-ul necesare sintezei substanțelor organice.",
    ["pigmenți clorofilieni în grane", "faza de lumină în grana", "faza de întuneric în stromă"], "U", 2),
],

en=[
 EN("Organite", "Construiți patru enunțuri afirmative, câte două pentru fiecare conținut, utilizând limbajul științific adecvat: mitocondria; aparatul Golgi.",
    ["Mitocondria", "Aparatul Golgi"],
    ["Mitocondria are membrană dublă, cea internă formând criste.", "Mitocondria este sediul respirației celulare și conține ADN propriu.",
     "Aparatul Golgi este alcătuit din dictiozomi cu membrană simplă.", "Aparatul Golgi participă la elaborarea secrețiilor și la formarea membranelor."]),
],

me=[
 ME("Nucleul", "Nucleul celular", ["membrană nucleară", "cromatină", "ADN", "nucleol", "informație genetică", "cromozomi"],
    "Nucleul este delimitat de membrana nucleară dublă prevăzută cu pori și conține cromatina, formată din ADN, ARN și proteine. În ADN este stocată informația genetică, iar în timpul diviziunii cromatina se condensează formând cromozomii. Nucleolul participă la biogeneza ribozomilor."),
],

gl=[
 ("celulă", "Unitatea structurală, funcțională și genetică a organismelor vii."),
 ("celulă procariotă", "Celulă fără nucleu delimitat de membrană, cu nucleoid; caracteristică bacteriilor și cianobacteriilor."),
 ("celulă eucariotă", "Celulă cu nucleu delimitat de membrană dublă și organite; întâlnită la protiste, fungi, plante, animale."),
 ("nucleoid", "Zonă a citoplasmei procariotelor în care se află ADN-ul circular, fără membrană nucleară."),
 ("mureină", "Substanță din peretele celulei procariote."),
 ("mozaic fluid", "Model al membranei: două straturi fosfolipidice străbătute de proteine."),
 ("hialoplasmă", "Citoplasma fundamentală, nestructurată, mediul proceselor metabolice."),
 ("organit celular", "Component al citoplasmei cu structură și rol specific."),
 ("mitocondrie", "Organit cu membrană dublă, sediul respirației celulare, cu ADN propriu."),
 ("criste mitocondriale", "Pliuri ale membranei mitocondriale interne, cu enzime oxido-reducătoare."),
 ("reticul endoplasmatic", "Rețea de tubuli și vezicule cu membrană simplă; neted sau rugos (granular)."),
 ("ribozom", "Organit fără membrană, din ARN și proteine, sediul sintezei proteinelor."),
 ("aparat Golgi", "Totalitatea dictiozomilor; rol în secreție și formarea membranelor."),
 ("dictiozom", "Formațiune discoidală, aplatizată, cu membrană simplă, componentă a aparatului Golgi."),
 ("lizozom", "Organit cu membrană simplă și enzime hidrolitice; digestie intracelulară."),
 ("centrozom", "Centrul celular, format din doi centrioli; dă naștere fusului de diviziune."),
 ("vacuolă", "Veziculă cu membrană simplă (tonoplast) și suc vacuolar."),
 ("tonoplast", "Membrana vacuolei."),
 ("plastidă", "Organit specific celulei vegetale, cu membrană dublă și ADN propriu."),
 ("cloroplast", "Plastidă cu pigmenți clorofilieni, sediul fotosintezei."),
 ("grana", "Grămezi de tilacoide din cloroplast, unde se desfășoară faza de lumină."),
 ("stromă", "Substanța fundamentală a cloroplastului; faza de întuneric."),
 ("cromoplast", "Plastidă cu pigmenți roșii-portocalii (colorează fructe, petale)."),
 ("leucoplast", "Plastidă incoloră de depozitare: amiloplast, oleoplast, proteoplast."),
 ("cromatină", "ADN + ARN + proteine din nucleu; formează cromozomii."),
 ("nucleol", "Corpuscul din nucleu cu ARN; biogeneza ribozomilor."),
 ("carioplasmă", "Substanța fundamentală a nucleului (nucleoplasma)."),
],

cd=[
 ("Ce organite au membrană dublă?", "Mitocondriile și plastidele (cloroplaste, cromoplaste, leucoplaste)."),
 ("Ce organite sunt fără membrană?", "Ribozomii, centrozomul (și cilii/flagelii)."),
 ("Ce organite au membrană simplă?", "Reticulul endoplasmatic, aparatul Golgi, lizozomii, vacuolele."),
 ("Din ce este alcătuit peretele celular la plante / fungi / procariote?", "Celuloză (plante) / chitină (fungi) / mureină (procariote)."),
 ("Unde se desfășoară faza de lumină și unde faza de întuneric?", "Lumină: grana (tilacoide). Întuneric: stroma."),
 ("Ce rol au lizozomii?", "Digestia intracelulară (fagocitoză) prin enzime hidrolitice."),
 ("Ce conține cromatina?", "ADN, ARN și proteine."),
 ("Ce celule sunt anucleate la maturitate?", "Hematiile adulte și trombocitele (fragmente celulare)."),
],

cmp=[
 dict(title="Celula procariotă vs eucariotă", cols=["Criteriu", "Procariotă", "Eucariotă"],
      rows=[["Nucleu", "nucleoid, fără membrană", "nucleu delimitat de membrană dublă cu pori"],
            ["Material genetic", "cromozom circular", "cromozomi (ADN + proteine)"],
            ["Organite cu membrană", "absente", "prezente"],
            ["Perete celular", "mureină", "celuloză (plante), chitină (fungi), absent (animale)"],
            ["Exemple", "bacterii, cianobacterii", "protiste, fungi, plante, animale"]]),
 dict(title="Organite după tipul de membrană", cols=["Dublă", "Simplă", "Fără membrană"],
      rows=[["mitocondrii", "reticul endoplasmatic", "ribozomi"], ["plastide", "aparat Golgi", "centrozom"], ["", "lizozomi, vacuole", ""]]),
],
)
